spring:
  application:
    name: hvlstajproject
  jackson:
    mapper:
      accept-case-insensitive-enums: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hvlstajproject
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: hvlstajproject
    liquibase-schema: hvlstajproject

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: hvlstajproject
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  packages-to-scan: com.example.hvlstajproject
  paths-to-match: /api/**